export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';

export const ADMIN_SIGNUP_REQUEST = 'ADMIN_SIGNUP_REQUEST';
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS';
export const ADMIN_SIGNUP_FAIL = 'ADMIN_SIGNUP_FAIL';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const ADMIN_UPDATE_REQUEST = 'ADMIN_UPDATE_REQUEST';
export const ADMIN_UPDATE_SUCCESS = 'ADMIN_UPDATE_SUCCESS';
export const ADMIN_UPDATE_FAIL = 'ADMIN_UPDATE_FAIL';
