export const BANNER_LIST_REQUEST = "BANNER_LIST_REQUEST";
export const BANNER_LIST_SUCCESS = "BANNER_LIST_SUCCESS";
export const BANNER_LIST_FAIL = "BANNER_LIST_FAIL";

export const PHONE_SELLING_LIST_REQUEST = "PHONE_SELLING_LIST_REQUEST";
export const PHONE_SELLING_LIST_SUCCESS = "PHONE_SELLING_LIST_SUCCESS";
export const PHONE_SELLING_LIST_FAIL = "PHONE_SELLING_LIST_FAIL";

export const LAPTOP_SELLING_LIST_REQUEST = "LAPTOP_SELLING_LIST_REQUEST";
export const LAPTOP_SELLING_LIST_SUCCESS = "LAPTOP_SELLING_LIST_SUCCESS";
export const LAPTOP_SELLING_LIST_FAIL = "LAPTOP_SELLING_LIST_FAIL";

